In [1]:
import scipy as sc
import numpy as np
import scipy.linalg as sal

In [3]:
#### 1st way of treating the diagonal
A = np.zeros((3,3))

In [6]:
for i in np.arange(3):
    A[i,i] = 2
for i in np.arange(2):
    A[i,i+1] = -1
    A[i+1,i] = -1
print(A)

[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]


In [13]:
E,V = sal.eig(A)
print(E)
print(V)

[3.41421356+0.j 2.        +0.j 0.58578644+0.j] /
[[-5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [ 7.07106781e-01  4.05405432e-16  7.07106781e-01]
 [-5.00000000e-01  7.07106781e-01  5.00000000e-01]]


In [10]:
print(E[0],E[1],E[2])

(3.4142135623730914+0j) (1.9999999999999998+0j) (0.5857864376269049+0j)


In [17]:
V1 =V[:,0]
V1.shape = (3,1)
V1

array([[-0.5       ],
       [ 0.70710678],
       [-0.5       ]])

In [27]:
#### ANOTHER WAY OF TREATING THE TRIDIAGONAL
B = np.zeros((2,3))
for i in np.arange(2):
    B[0,i+1] = -1
for i in np.arange(3):    
    B[1,i] = 2
print(B)

E,V = sal.eig_banded(B)     # THIS IS FOR UPPER BAND, for a lower band, the matrix needs to be tweaked and command will be E,V = sal.eig_banded(B, lower = true)
print(E)
print(V)

[[ 0. -1. -1.]
 [ 2.  2.  2.]]
[0.58578644 2.         3.41421356]
[[-5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [-7.07106781e-01  3.12250226e-16 -7.07106781e-01]
 [-5.00000000e-01  7.07106781e-01  5.00000000e-01]]
