In [3]:
import scipy as sc
import numpy as np
import scipy.linalg as sal

In [4]:
# Creating Null Matrix of desirable dimension
A = np.zeros((2,2))

In [5]:
# Replace and fill according to the needed elements
A[0,0] = 2
A[0,1] = 1
A[1,0] = 1
A[1,1] = 2
print(A)

[[2. 1.]
 [1. 2.]]


In [6]:
# Calculating Eigen Value and Eigen Vector
E, V = sal.eig(A)
print("Eigen Values=",E)
print("Eigen Vectors=",V)         # Obtained Eigen Vector is Normalised Right Eigen Vector.

Eigen Values= [3.+0.j 1.+0.j]
Eigen Vectors= [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [7]:
# Writing Eigen Values separately
print(E[0])
print(E[1])

(3+0j)
(1+0j)


In [8]:
S =V.shape   # So the Dimension or shape function does not follow the index system of starting from zero
print(S)

(2, 2)


In [9]:
# Identifying Eigen Vectors
print(V[:,0])  # Array for 1st Eigen vector , i.e. 1st Column
print(V[:,1])  # Array for 2nd Eigen vector, 2nd Column 

[0.70710678 0.70710678]
[-0.70710678  0.70710678]


In [10]:
V1 = V[:,0]
V1.shape=(2,1) # Shape function follows regular dimension Notation
print(V1)

[[0.70710678]
 [0.70710678]]


In [11]:
V2 = V[:,1]
V2.shape = (2,1)
print(V2)

[[-0.70710678]
 [ 0.70710678]]


In [21]:
# Inner Product (Scaler)
check1 = V[:,0] @ V1      #Scaler multiplication between BRA(row) array and KET(column) array of Eigen Vector 1
print(check1)             # Normality Check
check2 = V[:,1] @ V2
print(check2)             # Normality Check
check3 = V[:,0] @ V2
print(check3)             # Orthogonality Check

[1.]
[1.]
[2.23711432e-17]
